minio:
  endpoint: ${MINIO_ENDPOINT:http://111.9.116.135:9000}
  accessKey: ${MINIO_ACCESSKEY:minio}
  secretKey: ${MINIO_SECRETKEY:=[;._PL<0okm}
  bucket: ${MINIO_BUCKET:tmp}
ladybird:
  restful-exception:
    messages:
      upload_no_file:
        httpStatus: 400
        message: 缺少上传文件